commit today
Savichilya/Test1 pull request #4
Opened 2022-01-20 12:34 UTC by Savichilya

2022-01-20 14:20 UTC, savichmx requested changes
Измени метод updatePlayers так, чтобы он тоже принимал один параметр Player

2022-01-20 14:20 UTC, savichmx commented on src/com/company/repository/PlayersRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("INSERT INTO players(name_p, age) VALUES(?,?)", Statement.RETURN_GENERATED_KEYS)) {
ты должен при добавлении еще указывать айди футбольного клуба

2022-01-20 14:20 UTC, savichmx commented on src/com/company/repository/PlayersRepository.java
> +                players.setFoot_clubs(Foot_clubsRepository.getInstance().getById(resultSet.getInt("id_p")));
Ты пытаешься найти футбольный клуб по айди плеера. Айди плеера и айди футбольного клуба это разные айди

2022-01-21 19:41 UTC, savichmx requested changes

2022-01-21 19:41 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("INSERT INTO players(name_p, age) VALUES(?,?)", Statement.RETURN_GENERATED_KEYS)) {
ты еще должен сетать айди футбольного клуба

2022-01-21 19:41 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +                player.setFootballClub(FootballClubRepository.getInstance().getById(resultSet.getInt("id_p")));
ты опять ищешь футбольный клуб по айди плеера. Тебе нужно искать по айди футбольного клуба

2022-01-21 19:45 UTC, Savichilya commented on src/com/company/repository/PlayerRepository.java
> +                player.setFootballClub(FootballClubRepository.getInstance().getById(resultSet.getInt("id_p")));
тогда ошибку выдает

2022-01-21 19:46 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +                player.setFootballClub(FootballClubRepository.getInstance().getById(resultSet.getInt("id_p")));
какую ошибку

2022-01-21 20:10 UTC, savichmx requested changes

2022-01-21 20:10 UTC, savichmx commented on src/com/company/model/Player.java
> +    private Integer idFotballClub;
этого поля не должно быть

2022-01-21 20:10 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +            prepareStatement.setInt(2, player.getIdFotballClub());
тебе надо брать id из объекта footballCLub

2022-01-21 20:14 UTC, Savichilya commented on src/com/company/model/Player.java
> +    private Integer idFotballClub;
какого именно?

2022-01-21 22:02 UTC, savichmx commented on src/com/company/model/Player.java
> +    private Integer idFotballClub;
Это комментарий к 7-ой строчке, соответственно `idFotballClub`

2022-01-21 22:03 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +            prepareStatement.setInt(2, player.getIdFotballClub());
это комментарий к последней строчке (25), тебе показываются предыдущие, чтобы ты понимал контекст

2022-01-22 07:53 UTC, Savichilya commented on src/com/company/model/Player.java
> +    private Integer idFotballClub;
ты писал: "ты еще должен сетать айди футбольного клуба"
так я для этого и создал idFootballClub
А теперь удалить?

2022-01-22 10:14 UTC, savichmx commented on src/com/company/model/Player.java
> +    private Integer idFotballClub;
Ты его должен брать не из этого поля, а из поля footballClub

2022-01-23 17:32 UTC, savichmx requested changes

2022-01-23 17:32 UTC, savichmx commented on src/com/company/model/FootballClub.java
> +    public static Integer idFootballClub;
почему static?

2022-01-23 17:32 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +            prepareStatement.setInt(3, FootballClub.getIdFootballClub());
должно быть player.getFootballClub.getId()

2022-01-24 20:23 UTC, savichmx approved these changes

2022-01-25 17:14 UTC, merged