commit 29/01 23.35
Savichilya/Test1 pull request #6
Opened 2022-01-29 20:37 UTC by Savichilya

2022-01-30 09:19 UTC, savichmx requested changes

2022-01-30 09:19 UTC, savichmx commented on src/com/company/repository/FootballClubRepository.java
> +    public List<FootballClub> returnFootballClubsByYear(int a) throws SQLException {
называй переменный правильно, а не просто одной буквой

2022-01-30 09:19 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +    public List<Player> returnPlayersByName(String s) throws SQLException {
тут тоже

2022-01-30 09:19 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +           prepareStatement.setString(1, "s%");
ты не используешь переменную, а всегда одну и ту же строку `"s%"`

2022-01-30 09:19 UTC, savichmx commented on src/com/company/repository/FootballClubRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_fc FROM foot_clubs WHERE year_birth LIKE ?")) {
тут должно быть не `LIKE`, а знак `=`

2022-01-30 09:19 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_p FROM" +
ты просто всех игроков выводишь

2022-01-30 14:08 UTC, Savichilya commented on src/com/company/repository/PlayerRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_p FROM" +
так я же в main прописал, что мне нужно вывести

2022-01-30 14:10 UTC, Savichilya commented on src/com/company/repository/FootballClubRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_fc FROM foot_clubs WHERE year_birth LIKE ?")) {
тогда запрос не будет выполняться, у меня же все корректно выполняется и выводит то, что нужно

2022-01-30 14:10 UTC, Savichilya commented on src/com/company/repository/PlayerRepository.java
> +           prepareStatement.setString(1, "s%");
не понял, ты же сам мне сказал так сделать

2022-01-30 14:33 UTC, savichmx commented on src/com/company/repository/FootballClubRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_fc FROM foot_clubs WHERE year_birth LIKE ?")) {
почему не будет? Будет

2022-01-30 14:33 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +           prepareStatement.setString(1, "s%");
да, но я тебе сказал, чтобы ты потом символ `s` поменял на переменную метода

2022-01-30 14:39 UTC, savichmx commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
этот способ сработал бы, если бы у тебя все игроки были отсортированы по имени

2022-01-30 14:39 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_p FROM" +
этот код должен быть внутри этого метода, потому что у тебя метод называется returnPlayersSameName, а по факту он просто всех игроков выводит

2022-01-30 14:43 UTC, Savichilya commented on src/com/company/repository/PlayerRepository.java
> +           prepareStatement.setString(1, "s%");
тогда работать не будет

2022-01-30 14:44 UTC, Savichilya commented on src/com/company/repository/FootballClubRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_fc FROM foot_clubs WHERE year_birth LIKE ?")) {
в mysql он работает вместе с LIKE

2022-01-30 14:53 UTC, Savichilya commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
нет, он у меня выводит просто игроков через одного.
Я в запрос добавил "ORDER BY name_p ASC", что бы отсортировало по алфавиту, но у меня все равно выводит игроков через одного

2022-01-30 16:57 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +           prepareStatement.setString(1, "s%");
У тебя сейчас выводит имена которые начинаются только на букву s, а ты попробуй вывести на букву m например

2022-01-30 16:58 UTC, savichmx commented on src/com/company/repository/FootballClubRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_fc FROM foot_clubs WHERE year_birth LIKE ?")) {
LIKE это для создания шаблонов, а тут тебе нужно какого-то конкретного года. Поэтому просто оператора `=` будет достаточно

2022-01-30 16:59 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_p FROM" +
этот код должен быть внутри этого метода, потому что у тебя метод называется returnPlayersSameName, а по факту он просто всех игроков выводит

2022-01-30 17:00 UTC, savichmx commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
потому что в этой строчке  `if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true)` нужно делать не `i++`, а `i+1`. Когда ты делаешь i++ это равносильно `i=i+1`, а когда ты делаешь `i+1`, то он не присваивает это значение переменной `i`

2022-02-01 16:43 UTC, Savichilya commented on src/com/company/repository/FootballClubRepository.java
> +        try (PreparedStatement prepareStatement = ConnectionHolder.getConnection().prepareStatement("SELECT name_fc FROM foot_clubs WHERE year_birth LIKE ?")) {
Кстати с "=" не работает

2022-02-01 16:47 UTC, Savichilya commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
работает, но при этом ошибку выдает какую-то

2022-02-01 16:47 UTC, Savichilya commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 16, Size: 16
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.company.Main.main(Main.java:18)

2022-02-01 16:57 UTC, savichmx commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
попробуй сам разобраться почему тебе выдает эту ошибку, советую использовать дебаг, чтобы понять

2022-02-01 17:00 UTC, Savichilya commented on src/com/company/Main.java
> +            if (players.get(i).getNamePlayer().equals(players.get(i++).getNamePlayer()) == true) {
если бы я умел им пользоваться))
короче я сделал так и нормально работает:
for (int i=0; i<players.size()-1; i++)

2022-02-02 12:08 UTC, merged